library(edgeR)

group <- factor(c(2, 2, 3, 3, 4, 4, 1, 1))
y <- DGEList(counts = cnts, group = group)
keep <- filterByExpr(y)
filtered_y <- y[keep, , keep.lib.sizes = FALSE]
norm_y <- calcNormFactors(filtered_y)
design <- model.matrix(~group)
dispers_y <- estimateDisp(norm_y, design)

#Perform quasi-likelihood F-test
fit <- glmQLFit(dispers_y, design)
qlf.2vs1 <- glmQLFTest(fit, coef = 2)
topTags(qlf.2vs1)
FDR <- p.adjust(qlf.2vs1$table$PValue)
sum(FDR<0.01)
edge_sig <- subset(qlf.2vs1$table, logFC>1 | logFC< -1)
edge_sig <- subset(edge_sig, logFC>1)
FDR <- p.adjust(edge_sig$PValue)
edge_sig <- cbind(edge_sig, FDR)
sum(FDR<0.01)
edge_sig <- subset(edge_sig, FDR<0.01)
#edge_sig <- subset(qlf.2vs1$table, FDR < 0.01)
write.csv(as.data.frame(edge_sig), 
          file="~/data/deg_confirm/edge_mine_up_s2.csv")

fit <- glmQLFit(dispers_y, design)
qlf.3vs1 <- glmQLFTest(fit, coef = 3)
topTags(qlf.3vs1)
FDR <- p.adjust(qlf.3vs1$table$PValue)
sum(FDR<0.01)
edge_sig <- subset(qlf.3vs1$table, logFC>1 | logFC< -1)
edge_sig <- subset(edge_sig, logFC>1)
FDR <- p.adjust(edge_sig$PValue)
edge_sig <- cbind(edge_sig, FDR)
sum(FDR<0.01)
edge_sig <- subset(edge_sig, FDR<0.01)
#edge_sig <- subset(qlf.2vs1$table, FDR < 0.01)
write.csv(as.data.frame(edge_sig), 
          file="~/data/deg_confirm/edge_mine_up_s2_2.csv")

fit <- glmQLFit(dispers_y, design)
qlf.4vs1 <- glmQLFTest(fit, coef = 4)
topTags(qlf.4vs1)
FDR <- p.adjust(qlf.4vs1$table$PValue)
sum(FDR<0.01)
edge_sig <- subset(qlf.4vs1$table, logFC>1 | logFC< -1)
edge_sig <- subset(edge_sig, logFC>1)
FDR <- p.adjust(edge_sig$PValue)
edge_sig <- cbind(edge_sig, FDR)
sum(FDR<0.01)
edge_sig <- subset(edge_sig, FDR<0.01)
#edge_sig <- subset(qlf.2vs1$table, FDR < 0.01)
write.csv(as.data.frame(edge_sig), 
          file="~/data/deg_confirm/edge_mine_up_s2_3.csv")

library(venn)
library(gplots)
prot1 <- read.csv("~/data/deg_confirm/edge_mine_up.csv", header = FALSE)
prot2 <- read.csv("~/data/deg_confirm/deseq2_mine_up.csv", header = FALSE)
data <- list(A = prot1$V1, B = prot2$V1)
venn(data)

library(venn)
library(gplots)
prot2 <- read.csv("~/data/deg_confirm/edge_mine_up_s2_2_rmdot.csv", header = FALSE)
prot1 <- read.csv("~/data/deg_confirm/edge_mine_up_s2_rmdot.csv", header = FALSE)
prot3 <- read.csv("~/data/deg_confirm/edge_mine_up_s2_3_rmdot.csv", header = FALSE)
prot4 <- read.csv("~/data/deg_confirm/edge_mine_up_s2_rmdot_merge.csv", header = FALSE)
public <- read.csv("~/data/deg_confirm/edge_public_up.csv", header = FALSE)
data <- list(KHM_pipeline_edge = prot1$V1, Public_pipeline_edge_up = prot2$V1)
venn(data)

data <- list(KHM_pipeline_edge = prot1$V1, Public_pipeline_edge_up = prot3$V1)
venn(data)

data <- list(KHM_pipeline_edge = prot2$V1, Public_pipeline_edge_up = prot3$V1)
venn(data)

data <- list(A = prot2$V1, B = prot3$V1, C = prot1$V1)
venn(data)

data <- list(KHM_pipeline_edge = prot4$V1, Public_pipeline_edge_up = public$V1)
venn(data)

